@startuml

skinparam actorStyle awesome
"User" as User
(Choose Cloud Service) as ChooseCloudService
(Enter Authorization Key) as EnterAuthKey

User --> ChooseCloudService
(ChooseCloudService) .> EnterAuthKey : include

note right of User: The use can project manage,\n owner, devloper, billing manager.

note right of EnterAuthKey: This is the authen method \n for DigitalOcean.


@enduml
