@startuml

skinparam actorStyle awesome
"User" as User
( Billing Alert) as BillingAlert
(Enter alert amount) as EnterAlertAmount
(Choose notification methods) as ChooseNotificationMethods
(Add alerts) as AddAlerts

User --> BillingAlert
(BillingAlert) ..> AddAlerts 
(AddAlerts) ..> EnterAlertAmount : include
(AddAlerts) ..> ChooseNotificationMethods : include
note right of User:   Owner & Billing manager.



@enduml
