@startuml

skinparam actorStyle awesome
"User" as User
(Manage container) as ManageContainer
(View Container) as ViewContainer
(Start container) as StartContainer
(Stop container) as StopContainer
(Remove container) as RemoveContainer

User --> ManageContainer

ManageContainer ..>ViewContainer: include
ManageContainer ..>StartContainer: include
ManageContainer ..>StopContainer: include
ManageContainer ..>RemoveContainer: include
note right of User: The user can be developer,\n project manager, owner.
note right of ManageContainer: Manage container in VPS.

@enduml
