@startuml

skinparam actorStyle awesome
"User" as User
(Choose Manage Billing) as ChooseManageBilling
(Show Billing History) as ShowBillingHistory
(View Invoice Information) as ViewInvoiceInformation

User --> ChooseManageBilling
(ChooseManageBilling) .> ShowBillingHistory : extend
(ChooseManageBilling) .> ViewInvoiceInformation : extend
note right of User:   Owner & Billing manager.



@enduml
