@startuml

skinparam actorStyle awesome
"User" as User
( Manage Account) as ManageAccount
( Create Account ) as CreateAccount
( Edit Account ) as EditAccount
( Delete Account) as DeleteAccount
( View Account) as ViewAccount

User --> ManageAccount
(ManageAccount) ..> EditAccount : include
(ManageAccount) ..> CreateAccount : include
(ManageAccount) ..> DeleteAccount : include
(ManageAccount) ..> ViewAccount : include
note right of User:   Owner 



@enduml
