@startuml Api Management in front of AKS

title Web Application Architecture
actor "End User" as User


card WebBrowser as Browser

frame Application{

    
        cloud "Digital Ocean VPS" as DOVPS {
            frame AppFrontend{
        node "Web Server" as WebServer
    }
            frame AppBackend{
        node "NodeJS Server" as NodeServer
    }
        }
    

    

    

    frame ThirdPartyServices as ThirdPartyServices{
        node "Cloud APIs"
        node "Email Notification"
        node "SMS Notification"
    }

    database MongoDB as DB
}

NodeServer -> ThirdPartyServices
NodeServer <--> DB
WebServer <- NodeServer
WebServer <- Browser
Browser <-- User

@enduml